WITH USERS AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
    )

SELECT YEAR(o.SALES_DATE) AS YEAR,
    MONTH(o.SALES_DATE) AS MONTH,
    COUNT(DISTINCT o.USER_ID) AS PUCHASED_USERS,
    ROUND(COUNT(DISTINCT o.USER_ID) / (SELECT COUNT(USER_ID) FROM USERS), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE AS o
JOIN USERS AS u
ON o.USER_ID = u.USER_ID
GROUP BY YEAR(o.SALES_DATE), MONTH(o.SALES_DATE)
ORDER BY YEAR, MONTH