SELECT o.PRODUCT_ID, p.PRODUCT_NAME, (p.PRICE * SUM(o.AMOUNT)) AS TOTAL_SALES
FROM FOOD_ORDER AS o
LEFT JOIN FOOD_PRODUCT AS p
ON o.PRODUCT_ID = p.PRODUCT_ID
WHERE YEAR(o.PRODUCE_DATE) = 2022 AND MONTH(o.PRODUCE_DATE) = 5
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID