--서브쿼리 사용
SELECT *
FROM FOOD_PRODUCT
WHERE PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT)

--서브쿼리 사용 x -> 성능 문제 x
SET @MX := (SELECT MAX(PRICE) FROM FOOD_PRODUCT);

SELECT *
FROM FOOD_PRODUCT
WHERE PRICE = @MX